heat_template_version: 2013-05-23

parameters:
  external_network:
    type: string
    description: external network
    default: a4fd20bc-3679-4a87-a677-8b70a68ad417
  front_cidr:
    type: string
    description: internal cidr
    default: 172.16.110.0/24
  floatingip_vip:
    type: string
    description: floating_ip of vip of lb pool
    default: f6f94483-7b5b-406a-98d6-978c917ff705
  floatingip_manager:
    type: string
    description: floating_ip of manager node
    default: b0f53e3d-2f60-4327-9782-e0c2336f5116
     
resources:

  internal_network:
    type: IBM::Alchemy::Network
    properties:
      external_network: {get_param: external_network}
      front_cidr: {get_param: front_cidr}  

  keypair:
    type: IBM::Alchemy::Keypair
    
  manager:
   type: IBM::Alchemy::Manager 
   properties:
     network: {get_attr: [internal_network, front_net]}
     keypair: {get_attr: [keypair, keypair_id]}
     privkey: {get_attr: [keypair, key]}
     pubkey: {get_attr: [keypair, pubkey]}
     floatingip_id: {get_param: floatingip_manager}
  
  asg:
    type: IBM::Alchemy::LBGroup
    depends_on: [manager]
    properties:
      keypair: {get_attr: [keypair, keypair_id]}
      manager: {get_attr: [manager, server_id]}
      network: {get_attr: [internal_network, front_net]}
      subnet: {get_attr: [internal_network, front_subnet]}
      floatingip_id: {get_param: floatingip_vip}
      group_size: 1

outputs:
  manager:
    description: manager node ip
    value: {get_attr: [manager, server_ip]}
  member_list:
    description: member list
    value: {get_attr: [asg, member_list]}
  key:
    description: private key
    value: {get_attr: [keypair, key]}
  scale_up_url:
    description: >
      This URL is the webhook to scale up the group.  You can invoke
      the scale-up operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [asg, scale_up_url]}
  scale_down_url:
    description: >
      This URL is the webhook to scale down the group.  You can invoke
      the scale-up operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [asg, scale_down_url]}
  asg_size:
    description: >
      This is the current size of the auto scaling group.
    value: {get_attr: [asg, asg_size]}
  manager_floatingip:
    description: floatingip of manager node
    value: {get_param: floatingip_manager}
  lb_vip_floatingip:
    description: floatingip of lb vip 
    value: {get_param: floatingip_vip}
  
