heat_template_version: 2013-05-23
outputs:
  contents:
    description: deploy contents
    value: |
      H4sIAAAAAAACA+0YaVPbSDaf+1c8hAiQlE5fYGJmGIZsUjsJKezUViqbMbLUthXLklZqA17wf9/X
      h+w2dhJmp6ZqP6xcZam7X79+99Fuy8Wf12rWXa/p+q7req7bajXw3WrUq385LV5+s9XymvW6L4cN
      Vz31lj/IMlayIsjtcvxsd8cZxKkzCMoxIWEE5kEUF2kwpWC6h4Te0RD80+cenIJzExROko2c1X4c
      kW73TWe/LMdgZdBlRRyyN1nJ/k7n52MaTuJ01EkzvnaepSkNWS+e0mzGOjWwYqAsdOKoX5TBPume
      f0A8Yf5n8by76J31375/2+sjYU6WMyeieZLNHQGUxgy5lkBvLru9bodPj/GkkoTjaRbByzswdRxk
      bQRlkDDxR9zHKvHc+laV+OsqaSgV1d3Vg0Q8W8eH7+YfU3GFr1Zr1DRe1zQs9KmpUsDgh9AxIe/+
      dtV/f/buomN65N0n9enzz6vL3/DzXk3u7X12reMvLxYEsVI0mI55gLZzvTSd+1/Oum/63cuPV+cX
      n90vi+sTyG8jtCc2djuGUEVK2W1WTJAERothENLSjhy+bofDkUEGWRp9F1QASNh4CJ/BGuKxfP8C
      rAB25FgALeDLCbAxTQngswu3QcyAQ0LJAhaHYvp2HCcUWDGjJxBlYoo/YcCWaB9gVNBcbYLnz2FQ
      0GCyBC0TiqueGEdZSskwJrswDSYUyllBISjCcXxD7dlglrKZHWZTiEvI0bKDQULJFgL4GlgheNv2
      rp1Pw3EGhqIAShoi38AywapBdOoEZbsQJjRIZzkM46JkJJ/ESQJBzqwRZUS9wZpDPitGVJi79YIU
      U7CKIQiVCA/QAC1LggYzlhV0mt1QgobBfXPf+d10ohMnGvD/II/5KxlY/IV85DNG+WcRDAYx418p
      nbEiS/knP8WJ9uWR0kkVVsfzW7Zre7bnRPqy1JeyyoWchNNTHUTIamnKC9AWufGS6kODITqrszwK
      GCVRPkHlWCjpYTzi+rUCIi3RMNU+Azp8oJzKWDNDlFAx7CyDkmDVmgYlWrjN14o4oppqp6itIDGQ
      WFPsFEsVUXGKNokKFHoYZkVIrTktQUNJKlt+9eri8jUKZKlERwEwGU/b0HRdwrXYD8KQ5jjRQ5NE
      W05ov6DhzdqYJ4I24ubyboszLNBDrrCSHG0rKH4MLOEI0icNlhY3cUh1LrjrFUysclscVrKgSUmf
      LhAUd5ZuOULM4xFZvpJ7pUnQBSYA+3H0HRwVmb237y4uP/Y6x64Ynl9+fN/ruFrA+Swj1Qo7uqI6
      oTpIGUU+G3AD0mKTtIx/oIvzOIFsgjp/hM4ESmS4LcFoNaFzY7lRWamgxgCUGA4UpetGun7SJj1p
      xiCiDNMxeuVgDsqIjPXNdxhuveUURsX1iNlYjqV4zIMD8fGycXi4FkxVkOMJuBI0ZRjDMIpyENvY
      TMnNp6TkVr3eaIlxS0vJ0hwfZ2XXr2H6bTbr38/KS5S+u4HSwfAR2GVSPtsgt/UU3KuMvyK3VuFG
      6xWoKyfbf7Ff+Ro/dkNCnvsNCdW0I+utWq0uJxoaO1wTG1VL64/xsJKP73sy3GfhBM2LM5FmN4Ec
      ch7CaWSXYRFjTFIcldkMXbstfK/tOHKxXGIYK7AZ+mgbePxRE6Mim+VrM+WYJkkbVoWSnGZ0micY
      7NvwNU6/bkiv1vKfYF9YcXuPq3AlvYrkDUvwn1L71RvNpi/U4leWwNWpI17JQi8Dwbq7IQRLJgrO
      rMRKMB5gYsbIhnVOFpXOmLG8hC/w8AD3W+MqH2MDkJZ5VjBLgBMtSaoM+YRdmJOskBYsHsaYnTBE
      W3OxDcMVBNENRm/84iEWI9l4kqOS8yPXzrMssctJuVosbawR20cubuBJSixA48jzji6Ojl/Xzo49
      /+i4dY5CPvv1l9etJhpbo+WfN/yme/wr0RKjCMRcFtK2SjuJS4bVppIjH5GIDkBQj+QgqC3X8iL7
      ioHQzoqRg2ViBrJWQ45nJZtjOI5Tkdu2CCkMwjGFPMNAPQeJzaLpKE43Zbi2yqVFqgQkV1TuIWpU
      zFKwIgjjoshKsm6/ntvwn9JFcvuVY3/ZstTqzTUzu6WDbc0kFlVT6khBOKKwwuhe1VeHJM5xGA9l
      CSUq8gdRYRvIG0P9R0XbeAhuJ7B/nxdY/IPpL/bFhPW6vTZ5SFR24D0jvEfsbTD5QVgxxWlE7+wx
      myYK5u0HXLyP8wUu6qskn6P9o8Cm0I3R8embXu9DVxofmtZzIjKZ+zgK+K2npIRVDF1FAd+TUhTS
      ++/jnRT+Xx3s6rXa04zFbQgGcY+ylabbEom6n2YRfWwmu0hxMOJMLUHgFf/vx/kpGjeW3HcEO9Q+
      rzixH6w61ymdDmjRl7Vj/5r7Ehgv9z5Ze1NrL7L2esY1b2yNquU17yskC9Xsblx2/M9dZaz68etl
      U2KV1+Rj9+KqI73qT1x3dD911ZzWHIk+X8qWkOEsDRmvs2Ss6guQg0Mik0KShUECnCh+XbCa4V7t
      a+OhBKmJKeHf1r+w4IxzA0yxRrSa9CcDdrBpcrEOhRO9DpWui7vA5Hu462q7sTpcaPTytrcvMwM2
      LUE0f0Q0Rpy04zcaj6j29AsClXXE9rWC3eS7wcLw624ryE2unZ9FfFkumGhZ+oJo81d3DJwa86dV
      rbvBiqq8t7Eilyrav3GLoVXOFgMfTFU/Y8ZlNr9lWFXsB9+Bqm5AeAd4+K0LENdurHGifJlTKL+l
      ORzISG+qZUNdugmD3Ij5h+qK599gLlGg7Jf2IYI4bxyuZf+/QrVQJFs3sP/7P3ftF/sVE4Z5z419
      IW6yDHgosSgBa4bLtyFYyTW8BA9UB6LRLTehFvmRC96W8BAm/EOAoSEhObDyKN13dPIrznXGnwC8
      9FqibnEKyJJIXkvG6TAjohHl9RPmfWOFwuDFAsY2vjSiKW86DYcnBcfGWWeSZrepPBchrzTF8HN0
      h8BuK0DTvKFkw8uWZPI9sjfTuzXeoXIAeUmz4hpFrjtIxarBwU7BYdNcitLQNlbXsT/eqmLgCcjr
      3eDl3do8Ip1GHaOcRdnaPCzvbTQ9GGTbaSZiWElJY1jGjg0P1hDybTJe8/ZZXJcIBGicSxgsU/iV
      I+UlgqrylHwhAMz9SjFyo2UF5TwNv40AN6zXMe6PH2/7bE0b9K7O3v52cbWzs/Ps/89f8PwHP8uQ
      dgAaAAA=
